# VARIABLES
variables:
  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"

# DEFAULT
default:
  image: trion/ng-cli

# STAGES
stages:
  - build
  - sonarcloud-check

# BUILD MAIN BRANCH
build-main:
  stage: build
  before_script:
    - npm ci
  script:
    - ng build --prod
  artifacts:
    expire_in: 1 week
    paths:
      - dist/
  tags:
    - docker
  only:
    - main

# BUILD MERGE-REQUESTS
build-merge-requests:
  stage: build
  before_script:
    - npm ci
  script:
    - ng build --prod
  tags:
    - docker
  only:
    - merge_requests

# SONARCLOUD CHECK
sonarcloud-check:
  stage: sonarcloud-check
  image:
    name: sonarsource/sonar-scanner-cli:latest
    entrypoint: [""]
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  script:
    - sonar-scanner
  only:
    - merge_requests
    - main
